FROM mcr.microsoft.com/vscode/devcontainers/rust:2-bullseye@sha256:40d3fd4c8dd8322bca3dcc4930dd8b9b0e49ab0677df642f0e10459facb874fb

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
