FROM mcr.microsoft.com/vscode/devcontainers/rust:1-bullseye@sha256:58aad28b8450ad10f2ae4e38796104b493e6a77215c8e7639095c6ec0920ef07

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
