FROM mcr.microsoft.com/vscode/devcontainers/rust:1-bullseye@sha256:245ee7061d05051996dc24a869ed3e309142b1089feb342e410fb0ac42957dad

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
