name: Security audit

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: action-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
